name: Release

on:
  push:
    tags:
      - v*.**

jobs:
  build:
    name: ${{ matrix.os }}/${{ matrix.arch }} Node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node: [ 16, 18, 20 ]
        arch: [ x64 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # See https://github.com/nodejs/node-gyp/issues/2869
      - name: Fix node-gyp and Python
        run: python3 -m pip install packaging setuptools

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: |
            args: [--ignore-scripts]

      - name: Use Node.js  ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
          cache: "pnpm"

      - name: Build binary
        run: pnpm binary:build

      - name: Pack binary
        run: pnpm binary:pack

      - name: Release
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm binary:release
